mqtt:
  hostname: 127.0.0.1
  port: 1234 #defaults to 1883
  user: test
  password: test
deviceName: test
client_id: test
timezone: Europe/Brussels
update_interval: 60 #Defaults to 60
sensors:
  wifi_strength: true
  wifi_ssid: false
  available_updates: true
  external_drives:
    Drive1: /boot/
